name: Lint
on: [push, pull_request]

jobs:
  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v4
  check-spelling:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run cspell
        uses: zwaldowski/cspell-action@v1
        with:
          paths: "**/*.md"
          config: .github/cspell.json
